package com.actionTableAdmin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class action extends javax.swing.JPanel {

    public action() {
        initComponents();
    }

    public void initEvent(TableActionEvent event, int row){
        cmbEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onEdit(row);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbEdit = new com.actionTableAdmin.actionButton();

        cmbEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/pencil.png"))); // NOI18N
        cmbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.actionTableAdmin.actionButton cmbEdit;
    // End of variables declaration//GEN-END:variables
}
